name: bali_kuliner
description: Aplikasi panduan kuliner khas Bali

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # State Management
  provider: ^6.0.5

  # Shared Preferences
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.2.2

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1

  # QR Code
  qr_flutter: ^4.1.0
  # qr_code_scanner: ^1.0.1  # Commented out due to Android compatibility issues

  # Image
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # HTTP
  http: ^1.1.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1

  # Permissions
  permission_handler: ^11.0.1

  # URL Launcher
  url_launcher: ^6.1.7
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
